// <auto-generated />
namespace QuizWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MultileResponse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MultileResponse));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251220344_MultileResponse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
