//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite navigarea in chestionar.
        /// </summary>
        internal static string AllowNavigate {
            get {
                return ResourceManager.GetString("AllowNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza intotdeauna aceleasi intrebari.
        /// </summary>
        internal static string AlwaysGenerate {
            get {
                return ResourceManager.GetString("AlwaysGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspuns.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varianta raspuns corecta.
        /// </summary>
        internal static string AnswerDescription {
            get {
                return ResourceManager.GetString("AnswerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebare la care s-a raspuns.
        /// </summary>
        internal static string Answered {
            get {
                return ResourceManager.GetString("Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspuns la momentul.
        /// </summary>
        internal static string AnsweredOn {
            get {
                return ResourceManager.GetString("AnsweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspunde la intrebare.
        /// </summary>
        internal static string AnswerQuestion {
            get {
                return ResourceManager.GetString("AnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspunsuri.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebarea anterioara.
        /// </summary>
        internal static string BackAnswerQuestion {
            get {
                return ResourceManager.GetString("BackAnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inapoi la Lista.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume utilizator sau parola sunt gresite!.
        /// </summary>
        internal static string BadUserNameOrPassword {
            get {
                return ResourceManager.GetString("BadUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma raspunsul.
        /// </summary>
        internal static string ConfirmAnswer {
            get {
                return ResourceManager.GetString("ConfirmAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuare examen.
        /// </summary>
        internal static string ContinueTest {
            get {
                return ResourceManager.GetString("ContinueTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga varianta de raspuns.
        /// </summary>
        internal static string CreateAnswer {
            get {
                return ResourceManager.GetString("CreateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stergere.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa stergeti?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleza.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenume.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prima pagina.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acasa.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import fisier.
        /// </summary>
        internal static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensia fisierului nu este permisa! (se accepta doar .csv sau .xls).
        /// </summary>
        internal static string InvalidExtension {
            get {
                return ResourceManager.GetString("InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este raspuns corect.
        /// </summary>
        internal static string IsAnswer {
            get {
                return ResourceManager.GetString("IsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima pagina.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logare.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconectare.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatorie definirea variantei de raspuns.
        /// </summary>
        internal static string MandatoryAnswerDescription {
            get {
                return ResourceManager.GetString("MandatoryAnswerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatorie stabilirea categorie de intrebari.
        /// </summary>
        internal static string MandatoryQuestionCategory {
            get {
                return ResourceManager.GetString("MandatoryQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatorie definirea intrebarii.
        /// </summary>
        internal static string MandatoryQuestionDescription {
            get {
                return ResourceManager.GetString("MandatoryQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa stabiliti un numar de intrebari vizibile pe pagina.
        /// </summary>
        internal static string MandatoryQuestionsPerPage {
            get {
                return ResourceManager.GetString("MandatoryQuestionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa definiti numele chestionarului.
        /// </summary>
        internal static string MandatoryQuizName {
            get {
                return ResourceManager.GetString("MandatoryQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anul de studiu obligatoriu.
        /// </summary>
        internal static string MandatoryTestAnStudiu {
            get {
                return ResourceManager.GetString("MandatoryTestAnStudiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa introduceti numele.
        /// </summary>
        internal static string MandatoryTestFirstName {
            get {
                return ResourceManager.GetString("MandatoryTestFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa introduceti grupa.
        /// </summary>
        internal static string MandatoryTestGrupa {
            get {
                return ResourceManager.GetString("MandatoryTestGrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa introduceti prenumele.
        /// </summary>
        internal static string MandatoryTestLastName {
            get {
                return ResourceManager.GetString("MandatoryTestLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este obligatoriu sa introduceti numarul matricol.
        /// </summary>
        internal static string MandatoryTestNrMatricol {
            get {
                return ResourceManager.GetString("MandatoryTestNrMatricol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urmatorul.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebarea urmatoare.
        /// </summary>
        internal static string NextAnswerQuestion {
            get {
                return ResourceManager.GetString("NextAnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numar de intrebari.
        /// </summary>
        internal static string NumberOfQuestions {
            get {
                return ResourceManager.GetString("NumberOfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to din.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie de intrebari parinte.
        /// </summary>
        internal static string ParentQuestionCategory {
            get {
                return ResourceManager.GetString("ParentQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebare.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspunsuri la intrebare.
        /// </summary>
        internal static string QuestionAnswers {
            get {
                return ResourceManager.GetString("QuestionAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorii de intrebari.
        /// </summary>
        internal static string QuestionCategories {
            get {
                return ResourceManager.GetString("QuestionCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie de intrebari.
        /// </summary>
        internal static string QuestionCategory {
            get {
                return ResourceManager.GetString("QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ierarhia categoriilor de intrebari.
        /// </summary>
        internal static string QuestionCategoryHierarchyPath {
            get {
                return ResourceManager.GetString("QuestionCategoryHierarchyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire categorie de intrebari.
        /// </summary>
        internal static string QuestionCategoryName {
            get {
                return ResourceManager.GetString("QuestionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebare.
        /// </summary>
        internal static string QuestionDescription {
            get {
                return ResourceManager.GetString("QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolvare.
        /// </summary>
        internal static string QuestionDetails {
            get {
                return ResourceManager.GetString("QuestionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrebari.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul intrebarilor afisate pe pagina.
        /// </summary>
        internal static string QuestionsPerPage {
            get {
                return ResourceManager.GetString("QuestionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chestionar.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod chestionar.
        /// </summary>
        internal static string QuizCode {
            get {
                return ResourceManager.GetString("QuizCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire chestionar.
        /// </summary>
        internal static string QuizName {
            get {
                return ResourceManager.GetString("QuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chestionar.
        /// </summary>
        internal static string QuizTitle {
            get {
                return ResourceManager.GetString("QuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chestionare.
        /// </summary>
        internal static string Quizzes {
            get {
                return ResourceManager.GetString("Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amesteca ordinea raspunsurilor.
        /// </summary>
        internal static string RandomiseAnswersOrder {
            get {
                return ResourceManager.GetString("RandomiseAnswersOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amesteca ordinea intrebarilor.
        /// </summary>
        internal static string RandomiseQuestionsOrder {
            get {
                return ResourceManager.GetString("RandomiseQuestionsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţine-mă minte.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romana.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salveaza.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauta.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauta dupa cod.
        /// </summary>
        internal static string SearchByCode {
            get {
                return ResourceManager.GetString("SearchByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cautare dupa nume.
        /// </summary>
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alege chestionar.
        /// </summary>
        internal static string SelectQuiz {
            get {
                return ResourceManager.GetString("SelectQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alege chestionar - dupa cod.
        /// </summary>
        internal static string SelectQuizByCode {
            get {
                return ResourceManager.GetString("SelectQuizByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alege chestionar - dupa utilizator.
        /// </summary>
        internal static string SelectQuizByUser {
            get {
                return ResourceManager.GetString("SelectQuizByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acces STUDENT:.
        /// </summary>
        internal static string Studentmessage {
            get {
                return ResourceManager.GetString("Studentmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start EXAMEN.
        /// </summary>
        internal static string TakeQuiz {
            get {
                return ResourceManager.GetString("TakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat examen.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An studiu.
        /// </summary>
        internal static string TestAnStudiu {
            get {
                return ResourceManager.GetString("TestAnStudiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varianta raspuns data.
        /// </summary>
        internal static string TestAnswerDescription {
            get {
                return ResourceManager.GetString("TestAnswerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop EXAMEN.
        /// </summary>
        internal static string TestDone {
            get {
                return ResourceManager.GetString("TestDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenume.
        /// </summary>
        internal static string TestFirstName {
            get {
                return ResourceManager.GetString("TestFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        internal static string TestGrupa {
            get {
                return ResourceManager.GetString("TestGrupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID examen inexistent.
        /// </summary>
        internal static string TestIDNotFound {
            get {
                return ResourceManager.GetString("TestIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        internal static string TestLastName {
            get {
                return ResourceManager.GetString("TestLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul matricol.
        /// </summary>
        internal static string TestNrMatricol {
            get {
                return ResourceManager.GetString("TestNrMatricol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultate examen.
        /// </summary>
        internal static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultate examene.
        /// </summary>
        internal static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comuta-e raspuns corect.
        /// </summary>
        internal static string ToggleIsAnswer {
            get {
                return ResourceManager.GetString("ToggleIsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comuta-nu e raspuns corect.
        /// </summary>
        internal static string ToggleNotAnswer {
            get {
                return ResourceManager.GetString("ToggleNotAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se poate salva..
        /// </summary>
        internal static string UnableToSave {
            get {
                return ResourceManager.GetString("UnableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logare.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acces UTILIZATOR:.
        /// </summary>
        internal static string Usermessage {
            get {
                return ResourceManager.GetString("Usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume utilizator.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatori.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoare mai mica decat.
        /// </summary>
        internal static string ValueSmallerThen {
            get {
                return ResourceManager.GetString("ValueSmallerThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bine ati venit!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
